Repository GadiGoodi/back, pull requests merged in 2024-12, with the labels that each got.

#25 chore : spring security 의존성으로 인한 패키지 구조 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetails.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JWTUtil.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/global/config/SecurityConfig.java
Labels: refactor

#26 ARVU-99 feat:관리자 공지사항 서비스 로직 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/port/ManagerService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
Labels: ✨ Feature

#27 ARVU-99 feat:관리자 공지사항 Domain,Entity 수정코드
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/ManagerEntity.java
Labels: ✨ Feature

#28 ARVU-99 feat:관리자 공지사항 Controller,Response 작성 코드
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesList.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesPost.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesUpdate.java
Labels: ✨ Feature

#30 feat:관리자 공지사항 Repository Interface 코드
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/port/ManagerRepository.java
Labels: ✨ Feature

#31 ARVU-99 feat:관리자 공지사항 상세 조회 기능 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesDetail.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
Labels: ✨ Feature

#32 ARVU-97 feat: 코드 생성 기능
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/port/CodeService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/response/CodeResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/Code.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/dto/CodeCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/CodeDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/impl/CodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/mongo/CodeMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/port/CodeRepository.java
  src/main/java/com/gagoo/thiscoding/global/config/MongoReactiveConfig.java
Labels: 📬 API, ✨ Feature, ⚙ Setting

#36 refactor : joinCode 패키지 dto로 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/CertificationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/CertificationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/JoinCode.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/JoinCodeRedis.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/JoinCodeStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/JoinCodeStore.java
Labels: refactor

#39 fix: ErrorCode 내 CODE_ROOM_NOT_FOUND 추가
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 🐞 BugFix

#40 ARVU-94 feat: UserRepository 내 findById
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 🐞 BugFix, ✨ Feature

#42 config : 아마존 s3 설정 및 디펜던시 추가
  build.gradle
  src/main/java/com/gagoo/thiscoding/global/config/S3Config.java
Labels: ⚙ Setting

#45 feat : 이미지 경로 validator 커스텀 어노테이션 구현
  src/main/java/com/gagoo/thiscoding/global/s3/controller/validator/ImagePath.java
  src/main/java/com/gagoo/thiscoding/global/s3/controller/validator/PathValidator.java
  src/main/java/com/gagoo/thiscoding/global/s3/controller/validator/ValidateImagePath.java
Labels: 📬 API, ✨ Feature

#47 ARVU-94 chore: mongodb config
  build.gradle
  src/main/java/com/gagoo/thiscoding/global/config/MongoConfig.java
  src/main/java/com/gagoo/thiscoding/global/config/MongoReactiveConfig.java
Labels: 🔨 Fix

#46 ARVU-94 refactor: MongoReactive 관련 코드를 MongoRepository로 변경
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/port/CodeService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/impl/CodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/mongo/CodeMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/port/CodeRepository.java
Labels: 🔨 Fix, refactor

#48 ARVU-107 feat:마이페이지 내가 작성한 QnA 조회 기능 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageQnaService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageQnaServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature

#49 ARVU-99 fix:관리자 게시판 코드 BaseTimeEntity 상속
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesList.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/ManagerEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerNoticesRepositoryCustom.java
Labels: 🔨 Fix

#52 feat/mongo auditing setting
  src/main/java/com/gagoo/thiscoding/ThiscodingApplication.java
  src/main/java/com/gagoo/thiscoding/domain/maria/BaseTimeEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/AlarmEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesList.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/ManagerEntity.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/BaseTimeDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/global/config/JpaAuditingConfig.java
Labels: ✨ Feature, refactor

#51 Refactor/repository from service to model,to entity
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/port/ManagerService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerNoticesCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerNoticesUpdate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/ManagerEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/port/ManagerRepository.java
  src/main/java/com/gagoo/thiscoding/global/config/websocket/WebConfig.java
Labels: refactor

#50 ARVU-109 feat: UserRepository getById 메서드 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/controller/port/FriendService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/domain/Friend.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/domain/dto/FriendRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/infrastructure/FriendEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/infrastructure/impl/FriendRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/infrastructure/jpa/FriendJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/Exception/FriendAlreadyExistsException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/Exception/FriendNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/port/FriendRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#54 Chore/from create change
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/ManagerEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
Labels: 🐞 BugFix, 🔨 Fix

#56 ARVU-110 feat : qna 작성
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardCreatController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/BoardCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature

#55 feat: 회원 검증 메서드 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
Labels: 🔨 Fix

#57 chore : 파일 이름 수정
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardCreateController.java
Labels: 🔨 Fix

#58 fix : sendJoinCode http mapping 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/CertificationController.java
Labels: 📬 API, 🔨 Fix

#59 ARVU-106 feat : 회원 프로필 이미지 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UpdateProfile.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/UserEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
Labels: ✨ Feature

#62 fix : SecurityConfig에 필터 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtUtilImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/config/JwtFilterConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
Labels: 📬 API, 🔨 Fix, refactor

#63 feat : 회원 권한 검증 어노테이션 생성
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/global/config/InterceptorConfig.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/main/java/com/gagoo/thiscoding/global/security/AuthorizationException.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationInterceptor.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationRequired.java
Labels: 📬 API, ✨ Feature

#64 feat : SecurityUtils 생성
  src/main/java/com/gagoo/thiscoding/global/security/SecurityUtils.java
Labels: 📬 API, ✨ Feature

#61 ARVU-97 fix: 초대된 코드방 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/InviteCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/UserCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/UserCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/exception/OverCapacityException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/exception/UserCodeRoomAlreadyExistsException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/exception/UserCodeRoomNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/jpa/UserCodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/main/java/com/gagoo/thiscoding/global/pageDto/CustomPageDto.java
Labels: 🔨 Fix

#66 fix : cors preflight 에러 해결
  src/main/java/com/gagoo/thiscoding/global/config/InterceptorConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationInterceptor.java
Labels: 🐞 BugFix

#67 refactor : 유저관련 에러처리는 전역으로 처리
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/exception/UserNotFoundException.java
Labels: refactor

#68 ARVU-111 feat : 내 정보 조회
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/MyInfoResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/dto/MyInfo.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
Labels: ✨ Feature

#69 fix : 내정보 조회시 몽고디비 bean 등록 에러 해결
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/global/security/SecurityUtils.java
Labels: 🐞 BugFix

#72 ARVU-94 feat: 코드 웹 소켓 통신
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeSocketController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/dto/CodeSocket.java
  src/main/java/com/gagoo/thiscoding/global/config/websocket/WebSocketConfig.java
Labels: ✨ Feature

#73 ARVU- 94 feat: 코드방 입장 관련 Controller, Service, DTO, Response 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/CodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/CodeRoomEnterResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/dto/CodeRoomEnter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
Labels: ✨ Feature

#74 refactor : 의존성 주입 설정파일 추가
  src/main/java/com/gagoo/thiscoding/global/security/config/AuthenticationManagerConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/JwtLoginFilterConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/PasswordEncoderConfig.java
Labels: 🔨 Fix, refactor

#71 ARVU-103 fix: 코드방 참여 생성 관련 Controller, Service 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
Labels: 🔨 Fix

#75 refactor : jwt 설정과 상수용 클래스 생성
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/RefreshTokenStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtUtilImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/JwtProperties.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/constants/SecurityConstants.java
Labels: 🔨 Fix, refactor

#76 refactor : http servlet 관련 메서드 분리
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/global/utils/HttpServletUtils.java
Labels: refactor

#77 feat : 로그아웃
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
Labels: ✨ Feature

#79 ARVU-97 fix: UserCodeRoom 코드 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/UserCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/InviteCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/exception/OverCapacityException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/exception/UserCodeRoomAlreadyExistsException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/exception/UserCodeRoomNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/jpa/UserCodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/main/java/com/gagoo/thiscoding/global/pageDto/CustomPageDto.java
  src/main/java/com/gagoo/thiscoding/global/paging/PagingProcessor.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageRequest.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageResponse.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageResponseFactory.java
  src/main/java/com/gagoo/thiscoding/global/paging/exception/PageIndexException.java
Labels: 🔨 Fix

#80 ARVU-112 feat: qna 기본 검색
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/SearchDto.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
Labels: ✨ Feature

#81 Fix/dependency cycle
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/RefreshTokenStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtUtilImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/TokenReissueServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/JwtProperties.java
  src/main/java/com/gagoo/thiscoding/global/security/config/AuthenticationManagerConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/JwtLoginFilterConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
Labels: 🐞 BugFix

#82 fix : 리팩토링 도중 생긴 오타 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/global/security/JwtProperties.java
Labels: 🐞 BugFix

#83 ARVU-113 feat: qna 댓글 삭제 기능 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/Reply.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/ReplyEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/exception/ReplyNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/jpa/ReplyJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#84 ARVU-94 fix: 파일명 변경 관련 CodeResponse 필드 변경
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/port/CodeService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/response/CodeResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
Labels: 🔨 Fix

#85 ARVU-97 fix: InviteCodeRoom 필드 변수 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/InviteCodeRoom.java
Labels: 🔨 Fix
