Repository GadiGoodi/back, pull requests merged in 2024-11, with the labels that each got.

#1 chore QuerydslConfig 추가
  src/main/java/com/gagoo/thiscoding/global/config/QuerydslConfig.java
Labels: ⚙ Setting

#2 fix : 외래키 매핑 컬럼 이름 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/AlarmEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/infrastructure/FriendEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/report/infrastructure/ReportEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/UserCodeRoomEntity.java
  src/main/java/com/gagoo/thiscoding/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#3 ARVU-49 feat: 인증코드 전송
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/CertificationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/JoinCode.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/JoinCodeEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/JoinCodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/MailSenderImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/JoinCodeJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/UserJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/JoinCodeRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/MailSender.java
  src/main/java/com/gagoo/thiscoding/global/config/MailSenderConfig.java
Labels: 📬 API, ✨ Feature

#4 chore: 레디스 설정 추가
  build.gradle
  src/main/java/com/gagoo/thiscoding/global/config/RedisConfig.java
Labels: ⚙ Setting

#8 refactor: 레디스 콘피그 설정 변경
  src/main/java/com/gagoo/thiscoding/global/config/RedisConfig.java
Labels: 📬 API, 🔨 Fix

#9 fix: CrudRepository 사용으로 인한 원치않은 데이터 삽입
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/CertificationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/JoinCodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/JoinCodeRedisRepository.java
Labels: 🔨 Fix

#10 fix: redisTemplate 사용으로 ttl 수동 설정
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/JoinCodeRepositoryImpl.java
Labels: 🐞 BugFix, 📬 API

#12 chore: 상수나 클래스 패키지 생성으로인한 이동
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/contants/Role.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/contants/Social.java
Labels: 📃 Docs

#13 refactor: redis 키체인에 사용되는 :code 자체 클래스 생성
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/contants/CodeKeyChain.java
Labels: refactor

#14 refactor: 객체 불변성 보장
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/Social.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/Certification.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/UserEntity.java
Labels: refactor

#17 ARVU-97 feat: User Builder 생성자, UserEntity from, toModel 메서드 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/CodeRoomEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/UserEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/response/UserCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/UserCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/UserCodeRoomEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/jpa/UserCodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
Labels: ✨ Feature

#18 ARVU-48 feat : 회원가입
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/UserResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UserCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/UserEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/exception/AlreadyCreateEmail.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/exception/ExistUserNickname.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/UserJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/PasswordNotEqualException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/global/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 📬 API, ✨ Feature

#21 refactor : PostMapping에서 GetMapping으로 전환
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserController.java
Labels: 🔨 Fix, refactor

#20 chore : @Builder 삭제
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
Labels: 🔨 Fix, refactor

#19 chore : exception class 경로 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/JoinCodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/AlreadyCreateEmail.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/ExistUserNickname.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/JoinCodeNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/JoinCodeNotMatchException.java
Labels: 🔨 Fix, refactor

#22 ARVU-49 feat : 로그인
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/CustomUserDetails.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UserLogin.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/exception/UserNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/UserJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CustomUserDetailsService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/global/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/config/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/global/config/security/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 📬 API, ✨ Feature

#23 ARVU-94 build: webSocket 추가
  build.gradle
  src/main/java/com/gagoo/thiscoding/global/config/websocket/WebConfig.java
  src/main/java/com/gagoo/thiscoding/global/config/websocket/WebSocketConfig.java
Labels: ⚙ Setting
