Repository GadiGoodi/back, pull requests merged in 2025-02, with the labels that each got.

#132 test:관리자,Qna 테스트 코드 작성
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerRepositoryImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeManagerRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
  src/test/resources/sql/manager-board-test-data.sql
Labels: ✅ Test

#135 Refactor/login filter to json
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/LoginRequest.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/response/UserResponse.java
  src/main/java/com/gagoo/thiscoding/domain/auth/domain/Token.java
  src/main/java/com/gagoo/thiscoding/domain/auth/dto/LoginDto.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/PasswordServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/TokenFactoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/PasswordEncoderHolder.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/PasswordService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/TokenFactory.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/TokenProvider.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetails.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/common/util/HttpServletUtils.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationInterceptor.java
  src/main/java/com/gagoo/thiscoding/global/security/common/AuthConstants.java
  src/main/java/com/gagoo/thiscoding/global/security/config/JwtFilterConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/config/JwtProperties.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/exception/AuthorizationException.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/ThisCodingAuthentication.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/impl/SystemPasswordEncoder.java
  src/main/java/com/gagoo/thiscoding/global/security/service/port/PasswordEncoderHolder.java
Labels: refactor

#133 refactor:관리자 공지사항 findAll메서드를 CustomRepo 메서드로 변경 및 리팩토링
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerNoticesRepositoryCustom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/exception/NoticesNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/port/ManagerRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 🔨 Fix, refactor

#134 feat:셀프 조인을 통한 Qna 대댓글 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/Reply.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/dto/ReplyCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/ReplyEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/dto/ReplyList.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
Labels: ✨ Feature

#137 Refactor/rename file in s3
  .gitignore
  src/main/java/com/gagoo/thiscoding/domain/auth/common/AuthConstants.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/domain/Token.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SystemPasswordEncoder.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/FileController.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/port/FileService.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/response/UploadImageResponse.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/validator/ImagePath.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/validator/PathValidator.java
  src/main/java/com/gagoo/thiscoding/domain/file/controller/validator/ValidateImagePath.java
  src/main/java/com/gagoo/thiscoding/domain/file/domain/Images.java
  src/main/java/com/gagoo/thiscoding/domain/file/infrastructure/S3BucketImpl.java
  src/main/java/com/gagoo/thiscoding/domain/file/infrastructure/S3Properties.java
  src/main/java/com/gagoo/thiscoding/domain/file/service/S3Service.java
  src/main/java/com/gagoo/thiscoding/domain/file/service/port/S3Bucket.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/RefreshTokenStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/TokenReissueServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/common/uuid/infrastructure/SystemUuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/common/uuid/service/port/UuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/s3/controller/validator/ImagePath.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/global/utils/service/port/UuidHolder.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyWriteServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakePasswordEncoder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUuidHolder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: refactor

#139 fix : OAuth 로그인 에러 해결
  src/main/java/com/gagoo/thiscoding/domain/auth/domain/NaverUserInfo.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/JwtFilter.java
Labels: 🐞 BugFix, refactor

#141 test:QnA 댓글 테스트 코드 수정
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/domain/ReplyTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyReadServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
Labels: 🐞 BugFix, 🔨 Fix, ✅ Test

#142 feat : 비밀번호 변경, 초기화
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
Labels: ✨ Feature

#144 feat : 닉네임 변경
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/ResetPasswordRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/request/UpdateProfileNicknameRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UpdateProfile.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UpdateProfileImageRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
Labels: ✨ Feature

#145 feat : 네이버 로그인 구현
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/global/security/service/SecurityServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/service/port/SecurityService.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: ✨ Feature, refactor

#146 refactor : 레코드로 변경
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/ChangePasswordRequest.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/ResetPasswordRequest.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/request/UpdateProfileNicknameRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/AuthCode.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/UpdateProfileImageRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/AuthCodeRedis.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
Labels: refactor

#147 Refactor/move auth package
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/PasswordServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/TokenFactoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/PasswordService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/TokenFactory.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
Labels: refactor

#148 refactor : 레코드로 변경, @valid추가, 로그인 반환값에 role 추가
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/LoginRequest.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/response/UserResponse.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
Labels: refactor
