Repository GadiGoodi/back, pull requests merged in 2025-03, with the labels that each got.

#149 feat : 답변 작성 구현
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/request/BoardAnswer.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/BoardCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/domain/BoardTest.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardWriteServiceImplTest.java
Labels: ✨ Feature

#150 feat : 조회수 구현
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/BoardView.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardViewDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardViewRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardViewMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardViewServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardViewRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardViewService.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
Labels: ✨ Feature

#155 refactor: Invitations - 네이밍, 검증 로직, url, 반환값 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/InvitationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/InvitationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/InvitationCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/InvitedCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/dto/InvitationCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/jpa/CodeRoomCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/port/CodeRoomRepository.java
Labels: refactor

#152 refactor: UserCodeRoom - delete method 변경 및 검증 메서드 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/jpa/UserCodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
Labels: refactor

#153 feat: CodeRoom - Custom Exception 및 ErrorCode 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/exception/AlreadyJoinedCodeRoomException.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#154 feat: Alarm - delete, exist, getById 메서드 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/impl/AlarmRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/jpa/AlarmJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/service/port/AlarmRepository.java
Labels: ✨ Feature

#156 test: FakeAlarmRepository, FakeCodeRoomRepository, FakeUserCodeRoomRepository 추가 및 TestContainer 주입
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeAlarmRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeCodeRoomRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserCodeRoomRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test

#157 test: CodeRoom - 도메인 테스트, InvitationsServiceWriteTest 추가
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoomTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceWriteTest.java
Labels: ✅ Test

#158 refactor : 답변조회시 답변에 달린 댓글 갯수 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/dto/ReplyCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/AnswerListResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/AnswerList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
Labels: 📬 API, ✨ Feature, refactor

#159 feat: UserCodeRoom에 대한 Exception 및 ErrorCode 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/exception/NotUserCodeRoomParticipantException.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#161 refactor: UserCodeRoom 내 isAccepted 속성 삭제
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/UserCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/UserCodeRoomCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/UserCodeRoomEntity.java
Labels: refactor

#160 refactor: ParticipationController, ParticipationService 관련 메서드, 반환 값 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/ParticipationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/ParticipationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/jpa/CodeRoomCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
Labels: refactor

#162 test: CodeRoom 및 Participation 관련 테스트 코드 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/CodeRoomCreateResponseTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/CodeRoomEnterResponseTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/ParticipatingCodeRoomResponseTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoomTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/impl/CodeRoomRepositoryImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeCodeRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeCodeRoomRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserCodeRoomRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUuidHolder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/resources/sql/coderoom-test-data.sql
Labels: ✅ Test

#163 test:QnA 대댓글 조회 테스트 코드
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyReadServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyWriteServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
Labels: ✅ Test

#164 feat : 도커 빌드 파일, 젠킨스 파이프라인 작성
  Dockerfile
  Jenkinsfile
Labels: 📬 API, ✨ Feature

#167 refactor : 비밀번호 초기화
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/CertificationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/paging/service/port/PageableHolder.java
Labels: refactor

#168 del : 깃허브 액션으로 툴 변경
  Jenkinsfile
Labels: Delete

#169 Feat/ci workflow
  .github/workflows/ci.yml
Labels: ⚙ Setting

#170 EC2에 배포 워크플로우 생성
  .github/workflows/Deploy.yml
Labels: ⚙ Setting

#172 refactor: CodeCreate의 writerId 속성 삭제
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/Code.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/dto/CodeCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
Labels: refactor

#173 refactor: ParticipationServiceImpl 내 검증 메서드 수정 및 코드방 조회 메서드 분리
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
Labels: refactor

#176 Refactor/reset password role check annotation delete
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
Labels: refactor

#177 Refactor/visitor id provider
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/VisitorIdProvider.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/VisitorIdProviderImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
Labels: ✨ Feature, refactor

#178 Test(feat)/view count test
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardViewServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardViewRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/domain/BoardViewTest.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardReadServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardViewServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: ✨ Feature, ✅ Test

#179 refactor : ci 워크플로우 수정
  .github/workflows/ci.yml
Labels: ⚙ Setting, refactor

#180 test: CodeRoomServiceTest 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/impl/CodeRoomRepositoryImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: 🔨 Fix

#181 fix : 테스트코드 에러 해결
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/domain/ReplyTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardWriteServiceImplTest.java
Labels: 🐞 BugFix, ✅ Test

#166 feat:마이페이지 내가 작성한 QnA,답변 요청 분리 및 기능 구현
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageAnswer.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/MyPageAnswerList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature, 🔨 Fix

#182 fix : json 인식 불가 에러 해결
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
Labels: 🐞 BugFix

#184 fix : 비밀번호 변경 에러 해결
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/request/ResetPasswordRequest.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
Labels: 🐞 BugFix

#183 fix:Board 테스트 코드 에러 수정
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/MyPageAnswerList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/MyPageQnAList.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerRepositoryImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
Labels: 🐞 BugFix, ✅ Test

#185 fix:Board 테스트 코드 에러 수정
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
Labels: 🐞 BugFix

#186 feat: 답변 추천 및 취소
  src/main/java/com/gagoo/thiscoding/domain/maria/like/controller/LikeWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/controller/port/LikeService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/domain/Like.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/infrastructure/LikeEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/infrastructure/impl/LikeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/infrastructure/jpa/LikeJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/LikeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/exception/ExistLike.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/exception/LikeNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/port/LikeRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#188 chore : test용 yml파일 설정
  .github/workflows/ci.yml
  .gitignore
  src/test/resources/application-test.yml
Labels: ⚙ Setting

#189 test: CodeRoomRepositoryImplTest 불필요한 어노테이션 제외
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/impl/CodeRoomRepositoryImplTest.java
Labels: 🔨 Fix, ✅ Test

#193 fix : test 파일 인식 불가 해결
  src/test/java/com/gagoo/thiscoding/ThiscodingApplicationTests.java
  src/test/resources/application-test.yml
Labels: 🐞 BugFix, 🔨 Fix

#194 fix : jar 파일 못 찾는 에러 해결
  .github/workflows/build-and-test.yml
  .github/workflows/deploy.yml
  .github/workflows/docker-build-and-push.yml
  Dockerfile
Labels: 🐞 BugFix, 🔨 Fix

#195 refactor : 테스트 과정 분리
  .github/workflows/build-and-test.yml
  .github/workflows/deploy.yml
  .github/workflows/docker-build-and-push.yml
Labels: refactor

#198 refactor : h2db 테스트에서만 활성화
  build.gradle
Labels: refactor

#202 Setting/submodule change
  .gitmodules
  src/main/java/com/gagoo/thiscoding/global/common/response/ApiResponse.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImplTest.java
Labels: ⚙ Setting

#207 chore : gitignore yml 추가
  .gitignore
  src/main/resources/application.yml
Labels: ⚙ Setting, refactor

#209 fix : mailsender config path update
  .github/workflows/deploy.yml
  src/main/java/com/gagoo/thiscoding/global/config/MailSenderConfig.java
Labels: 🐞 BugFix

#210 test: CodeRoomRepositoryImplTest 관련 SQL 파일 구문 수정
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/impl/CodeRoomRepositoryImplTest.java
  src/test/resources/sql/coderoom-test-data.sql
Labels: 🐞 BugFix, ✅ Test

#213 fix : 게시판 작성시 작성일자 포함
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
Labels: 🔨 Fix

#214 refactor: CodeRoomService 내 검증 메서드 분리
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/CodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
Labels: refactor

#215 feat: 답변 조회 시 채택 및 좋아요 여부 조회
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/AnswerListResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/AnswerList.java
Labels: ✨ Feature

#216 feat : 로컬환경 도커 컴포즈 작성
  docker-compose.yml
Labels: ✨ Feature

#217 feat : Dockerfile-prod 생성
  .github/workflows/deploy.yml
  Dockerfile-prod
Labels: ✨ Feature

#218 refactor : 도커 실행 스크립트 ec2에서 관리
  .github/workflows/deploy.yml
Labels: refactor

#219 feat: 답변 채택
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/exception/ExistAdoptedAnswer.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/exception/InvalidAnswerUserException.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/exception/NotQnaUserException.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/main/java/com/gagoo/thiscoding/global/config/MongoConfig.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature, 🔨 Fix

#220 fix: 답변 추천 및 추천 취소 시, 추천 개수 증감이 안 되었던 부분 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/exception/LikeCountUnderFlowException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/LikeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature, 🔨 Fix

#221 test: CodeRoomSerivceTest, FakeBoardRepository 내 오류 수정
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
Labels: 🔨 Fix

#222 fix: BoardServiceImpl 내 오타 수정
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
Labels: 🔨 Fix

#223 refactor: CodeRoom, UserCodeRoom 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
Labels: refactor

#224 fix: 답변 조회 시, 비 로그인 상태일 경우 오류 수정
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: 🐞 BugFix, 🔨 Fix

#225 fix: 답변 조회 시, 정렬 방법 변경
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
Labels: 🔨 Fix

#226 refactor: CodeRoomCustomRepository 내 일부 메서드 호출 위치 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/port/CodeRoomRepository.java
Labels: refactor

#227 fix : 유저 정보 반환할 때 이미지 포함하도록 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/UserEntity.java
Labels: 🔨 Fix

#228 fix: coderoom queryDsl 조건을 BooleanExpression 메서드로 분리
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomCustomRepositoryImpl.java
Labels: 🔨 Fix

#229 feat: 친구 검색시 필요한 유저 검색 기능 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/UserProfile.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/UserJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
Labels: ✨ Feature

#230 fix: 코드방 입장 시, UserCodeRoom 내 isActivated 검증 후 활성화
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
Labels: 🔨 Fix

#232 feat : ansible 적용
  .github/workflows/deploy.yml
  ansible/ansible.cfg
  ansible/group_vars/all.yml
  ansible/group_vars/app_servers.yml
  ansible/inventory.ini
  ansible/playbooks/app-server.yml
  ansible/playbooks/common.yml
  ansible/playbooks/site.yml
  ansible/roles/common/handlers/main.yml
  ansible/roles/common/tasks/main.yml
  ansible/roles/docker/tasks/main.yml
  ansible/roles/docker/templates/deploy.sh.j2
  ansible/roles/java/tasks/main.yml
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
Labels: ✨ Feature, ⚙ Setting

#233 fix:공지사항 수정 시 category가 안바뀌는 오류 해결
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
Labels: 🔨 Fix

#234 feat: User nickname 반환 메서드 추가
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
Labels: ✨ Feature

#235 feat: Friend - custom exception, errorCode 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/controller/response/FriendInfoResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/Exception/AlreadyFriendRequestException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/Exception/FriendInvalidRequestException.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: ✨ Feature

#239 test: FakeUserRepository, FakeCodeRoomRepository 수정
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeCodeRoomRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
Labels: ✅ Test

#237 refactor: 쿠키 조회 메서드 리팩터링
  src/main/java/com/gagoo/thiscoding/global/common/util/HttpServletUtils.java
Labels: refactor

#238 refactor: 배포 스크립트 복사 디렉토리 위치 변경
  .github/workflows/deploy.yml
  ansible/ansible.cfg
  ansible/playbooks/app-server.yml
Labels: 🐞 BugFix

#240 refactor : 배포 스크립트 실행 로직 명시
  .github/workflows/deploy.yml
  ansible/playbooks/app-server.yml
  ansible/roles/common/handlers/main.yml
  ansible/roles/common/tasks/main.yml
Labels: refactor

#242 feat : 배포시 테스트코드 실행
  .github/workflows/deploy.yml
Labels: ✨ Feature, ⚙ Setting

#244 fix: CapacityOutOfBoundsException 패키지 경로 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/exception/CapacityOutOfBoundsException.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceWriteTest.java
Labels: 🔨 Fix

#245 refactor:friend
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/SecurityUtils.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/controller/FriendController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/jpa/UserJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
Labels: refactor
