Repository GadiGoodi/back, pull requests merged in 2025-04, with the labels that each got.

#246 fix: QnA 조회 시, 북마크 여부도 반환
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/QnaResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/QnaDetail.java
Labels: 🔨 Fix

#247 test: FakeBookmarkRepository, FakeLikeRepositoy 작성
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBookmarkRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeLikeRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test

#248 refactor: BoardServiceImpl 내 게시글 북마크, 답변 추천 여부 존재 여부 조회 메서드 변경
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
Labels: refactor

#249 feat:마이페이지 내가 북마크한 QnA 조회 기능 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/infrastructure/impl/BookmarkRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/infrastructure/jpa/BookmarkJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/service/port/BookmarkRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageBookmark.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/MyPageBookMarkList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature

#251 fix : 안 쓰는 오버라이딩 삭제
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: 🔨 Fix

#252 refactor : jwt 인증과정 에러처리 클래스 분리
  src/main/java/com/gagoo/thiscoding/domain/auth/exception/ClaimNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/auth/exception/ExpiredJwtTokenException.java
  src/main/java/com/gagoo/thiscoding/domain/auth/exception/MalformedFormJwtTokenException.java
  src/main/java/com/gagoo/thiscoding/domain/auth/exception/UnsupportedJwtTokenException.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/JwtTokenProvider.java
Labels: refactor

#253 feat : jwt 토큰 에러 처리 필터 추가
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/exception/ExceptionHandlingUtil.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/JwtExceptionHandlerFilter.java
Labels: ✨ Feature

#254 feat : jpa auditing config
  src/main/java/com/gagoo/thiscoding/global/config/JpaAuditingConfig.java
Labels: ✨ Feature

#255 fix : oauth 인증 후 홈으로 리다이렉트
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🔨 Fix, refactor

#257 test:마이페이지 북마크한 QnA 조회
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBookmarkRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImplTest.java
Labels: ✅ Test

#258 refactor : 소셜 로그인 유저 정보 반환 리팩토링
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/TokenFactoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/port/TokenFactory.java
Labels: refactor

#259 refactor : 토큰 재발급 계층 컨트롤러로 이동
  src/main/java/com/gagoo/thiscoding/domain/auth/dto/TokenDto.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/TokenReissueController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/TokenReissueService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/TokenReissueServiceImpl.java
Labels: refactor

#260 refactor : 권한 체크 에러처리 리팩토링
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/controller/BookmarkWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/InvitationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/ParticipationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/controller/FriendController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/controller/LikeWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationInterceptor.java
  src/main/java/com/gagoo/thiscoding/global/security/aop/AuthorizationRequired.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/AuthorizationExceptionFilter.java
Labels: refactor

#262 fix: 코드방 내 마지막 메시지 저장 및 전송
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeSocketController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/dto/CodeSocket.java
Labels: 🔨 Fix

#263 refactor: CodeDocument 및 관련 dto에 nickname 속성 추가
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/Code.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/CodeDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceTest.java
Labels: ✅ Test, refactor

#266 fix : 리프레시 토큰 검증
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/TokenReissueServiceImpl.java
Labels: 🐞 BugFix

#264 Test/fake object
  src/test/java/com/gagoo/thiscoding/domain/auth/service/PasswordServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeJwtProperties.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakePasswordEncoder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeRefreshTokenStore.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeTokenFactory.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeTokenProvider.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test

#267 feat:공통 Api Response 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/controller/BookmarkWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/InvitationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/ParticipationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/controller/LikeWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/CertificationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/TokenReissueController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
  src/main/java/com/gagoo/thiscoding/global/common/response/ApiResponse.java
  src/main/java/com/gagoo/thiscoding/global/common/response/ResponseInterceptor.java
  src/main/java/com/gagoo/thiscoding/global/exception/GlobalizedResponseException.java
Labels: ✨ Feature

#269 refactor : atk 접두사 추가 로직 변경
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/domain/Token.java
  src/main/java/com/gagoo/thiscoding/domain/auth/dto/TokenDto.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/gagoo/thiscoding/domain/auth/infrastructure/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/test/java/com/gagoo/thiscoding/domain/auth/domain/TokenTest.java
Labels: refactor

#272 refactor: 답변 목록 조회 시, 추천 여부 조회로 발생되는 N + 1 문제 수정
  src/main/java/com/gagoo/thiscoding/domain/maria/like/infrastructure/impl/LikeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/infrastructure/jpa/LikeJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/port/LikeRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeLikeRepository.java
Labels: refactor

#273 feat: 코드방 파일 목록 일괄 조회 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/port/CodeService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/response/CodeListResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/domain/dto/CodeList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/CodeDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/impl/CodeRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/infrastructure/mongo/CodeMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/port/CodeRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeCodeRepository.java
Labels: ✨ Feature, 🔨 Fix, ✅ Test

#274 chore : 클래스 이름 변경
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/filter/AuthExceptionFilter.java
Labels: chore

#275 refactor: Repository 예외 처리 구조 개선
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/PasswordServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/friend/service/FriendServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/like/service/LikeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/AlreadyCreateEmail.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/AuthCodeNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/AuthCodeNotMatchException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/ExistUserNickname.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/PasswordNotEqualException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/exception/TokenNotEquals.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/AuthCodeStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/TokenReissueServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/helper/UserFinder.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/service/CodeServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/service/SecurityServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/auth/service/PasswordServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeAuthCodeStore.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: refactor

#277 refactor : security filter chain
  src/main/java/com/gagoo/thiscoding/domain/file/controller/FileController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
Labels: refactor

#278 chore : dto 패키지 위치 변경
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/AuthCommandController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/CertificationController.java
  src/main/java/com/gagoo/thiscoding/domain/auth/controller/port/AuthService.java
  src/main/java/com/gagoo/thiscoding/domain/auth/service/AuthServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageCommandController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageQueryController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/CertificationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/request/AuthCodeRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/request/UpdateProfileImageRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/request/UserCreateRequest.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/UserProfileResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/dto/AuthCode.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/dto/Certification.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/dto/ReissueToken.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/AuthCodeRedis.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/AuthCodeStoreImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/MailSenderImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/AuthCodeStore.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/MailSender.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/domain/UserTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeAuthCodeStore.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeMailSender.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
Labels: refactor
