Repository GadiGoodi/back, pull requests merged in 2025-01, with the labels that each got.

#86 Fix/get top 10
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtFilter.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/domain/Answer.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/service/port/AnswerCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
Labels: 📬 API, ✨ Feature

#89 fix : 도큐먼트 분리했을 경우 기능 구현 시 복잡성이 더 증가하여 복구
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/controller/AnswerWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/controller/port/AnswerService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/domain/Answer.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/domain/dto/AnswerCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/infrastructure/AnswerRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/service/AnswerServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/service/port/AnswerCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/answer/service/port/AnswerRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/chat/infrastructure/ChatDocument.java
Labels: 🔨 Fix

#90 ARVU-112 fix: qna 검색
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/infrastructure/impl/ManagerNoticesRepositoryCustom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/SearchResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/Search.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardMongoCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/main/java/com/gagoo/thiscoding/global/paging/PageSize.java
  src/main/java/com/gagoo/thiscoding/global/paging/PagingProcessor.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageRequest.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageResponse.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/PageResponseFactory.java
Labels: ✨ Feature, 🔨 Fix

#93 ARVU-114 feat: 참여 중인 코드방 기능 관련 코드 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/port/CodeRoomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomParticipationsController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/response/ParticipationsResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/UserCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/ParticipationsRepositoryCustom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
Labels: 📬 API, ✨ Feature, 🔨 Fix

#94 Fix/user qna change board package
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/ManagerNoticesCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageQnaService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageQnaServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/MyQnaController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
Labels: 🔨 Fix

#95 feat : 댓글 작성, 조회
  src/main/java/com/gagoo/thiscoding/domain/maria/BaseTimeEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/Reply.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/dto/ReplyCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/ReplyEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/jpa/ReplyJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/dto/ReplyList.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/UserWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtUtilImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/exception/QnaNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/CustomPageDto.java
  src/main/java/com/gagoo/thiscoding/global/security/SecurityUtils.java
Labels: 📬 API, ✨ Feature

#96 refactor : 반환타입 명시를 위해 제네릭 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/CustomPageDto.java
Labels: 🔨 Fix, refactor

#97 feat : qna 작성, 전체조회
  src/main/java/com/gagoo/thiscoding/domain/mongo/BaseTimeDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/BoardCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/mongo/BoardMongoRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/QnaList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature

#98 ARVU-94 fix/code room create UUID
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/s3/infrastructure/SystemUuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/s3/service/S3ServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/s3/service/port/UuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/utils/infrastructure/SystemUuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/utils/service/port/UuidHolder.java
Labels: 🔨 Fix

#99 ARVU-94 fix/http method related code
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/UserCodeRoomCreateController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/code/controller/CodeCreateController.java
Labels: 🔨 Fix

#100 fix : qna id 추가
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/QnaList.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: 🔨 Fix

#101 feat : qna 상세조회 구현
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/jpa/ReplyJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/port/ReplyRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/QnaResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/impl/BoardRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/dto/QnaDetail.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/port/BoardRepository.java
Labels: ✨ Feature

#102 ARVU-97 fix: invitation 코드 분리 및 관련 패키지 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/controller/port/AlarmService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/domain/Alarm.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/AlarmEntity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/impl/AlarmRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/infrastructure/jpa/AlarmJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/service/AlarmServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/service/exception/AlarmNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/alarm/service/port/AlarmRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/InvitationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/InvitationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/InvitedCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/contants/Capacity.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/dto/InvitedCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/jpa/CodeRoomCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/exception/CapacityOutOfBoundsException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/response/UserCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/InviteCodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/domain/dto/UserCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/exception/OverCapacityException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/exception/UserCodeRoomAlreadyExistsException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/jpa/UserCodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/exception/UserCodeRoomNotFoundException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 🔨 Fix

#103 ARVU-113 fix: qna 댓글/답글 삭제 검증 부분 추가
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyWriteController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/exception/NotReplyAuthorException.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/impl/ReplyRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/infrastructure/jpa/ReplyJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/exception/ErrorCode.java
Labels: 🔨 Fix

#104 feat : cors 설정 추가
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
Labels: 📬 API, ✨ Feature

#105 refactor : findByEmail 에러처리
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/UserService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/impl/UserRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetailsService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/port/UserRepository.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
Labels: refactor

#106 test:관리자 테스트 코드 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/controller/port/ManagerService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/Manager.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerNoticesCreate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerNoticesUpdate.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/manager/service/port/ManagerRepository.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesDetailTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesListTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/mock/FakeManagerRepository.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceTest.java
Labels: ✅ Test, refactor

#107 ARVU-94 fix: participation 관련 패키지 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/ParticipationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/ParticipationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/ParticipatingCodeRoomResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomCustomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/jpa/CodeRoomCustomRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/controller/port/UserCodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/ParticipationsRepositoryCustom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/infrastructure/ipml/UserCodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/UserCodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/usercoderoom/service/port/UserCodeRoomRepository.java
Labels: 🔨 Fix, refactor

#108 refactor : paging aop 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/InvitationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/ParticipationController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/InvitationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/ParticipationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/ReplyReadController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/controller/port/ReplyService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/dto/MyInfo.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/BoardReadController.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/port/BoardService.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/paging/PagingProcessor.java
  src/main/java/com/gagoo/thiscoding/global/paging/aop/ConvertToOneBase.java
  src/main/java/com/gagoo/thiscoding/global/paging/aop/PageableConvertAspect.java
  src/main/java/com/gagoo/thiscoding/global/paging/dto/CustomPageDto.java
Labels: refactor

#109 fix : user 정보 반환
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/CustomUserDetails.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/infrastructure/security/JwtLoginFilter.java
Labels: 🐞 BugFix

#110 fix : 마이페이지 요청시 top10 유무만 반환
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/MyPageController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/MyPageService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/MyInfoResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/response/Top10StatusResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/dto/MyInfo.java
Labels: 🔨 Fix

#111 refactor : PasswordEncoderHolder 적용
  src/main/java/com/gagoo/thiscoding/domain/maria/user/domain/User.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/SystemPasswordEncoder.java
  src/main/java/com/gagoo/thiscoding/global/security/service/port/PasswordEncoderHolder.java
Labels: refactor

#112 test : User 순수 도메인 비지니스 로직 테스트 추가
  build.gradle
  src/test/java/com/gagoo/thiscoding/domain/maria/user/domain/UserTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakePasswordEncoder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test

#113 test:관리자 given/when/then 패턴 명시
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesDetailTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/controller/response/ManagerNoticesListTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/domain/ManagerTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/manager/service/ManagerServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeManagerRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: 🔨 Fix, ✅ Test, refactor

#114 test : 인증코드 발송, 검증 테스트
  src/main/java/com/gagoo/thiscoding/domain/maria/user/controller/port/CertificationService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeJoinCodeStore.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeMailSender.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test

#115 refactor(test) : 인증코드 발급과 확인 리팩토링
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeMailSender.java
Labels: ✅ Test, refactor

#116 test : 잘못된 이메일, 인증코드로 요청시 발생하는 에러 테스트 추가
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeMailSender.java
Labels: ✅ Test

#117 test : Reply 순수 도메인 비지니스 로직 테스트 작성
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/domain/Reply.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/domain/ReplyTest.java
Labels: ✅ Test

#119 refactor(test) : 의존성 주입 직접하지 않고 테스트 컨테이너에서 주입하도록 변경
  src/test/java/com/gagoo/thiscoding/domain/maria/user/service/CertificationServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
Labels: ✅ Test, refactor

#120 test : 테스트용 FakeRepository 구현
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeBoardRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
Labels: ✅ Test

#121 refactor : uuid random 반환타입 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/CodeRoomEntity.java
  src/main/java/com/gagoo/thiscoding/global/s3/service/S3ServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/utils/infrastructure/SystemUuidHolder.java
  src/main/java/com/gagoo/thiscoding/global/utils/service/port/UuidHolder.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUuidHolder.java
Labels: refactor

#122 refactor : SecurityUtils hexagonal port
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/InvitationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/MyPageServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/user/service/UserServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/service/BoardServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/config/SecurityConfig.java
  src/main/java/com/gagoo/thiscoding/global/security/infrastructure/SecurityUtilsImpl.java
  src/main/java/com/gagoo/thiscoding/global/security/service/port/SecurityUtils.java
Labels: refactor

#123 refactor : 게시판 기본키가 String인 것을 감안하여 부모 게시물 필드 타입 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/response/CodeRoomCreateResponse.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/ParticipationServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/MyPageQnA.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/controller/response/SearchResponse.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/Board.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/BoardCreate.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/domain/dto/Search.java
  src/main/java/com/gagoo/thiscoding/domain/mongo/board/infrastructure/BoardDocument.java
  src/main/java/com/gagoo/thiscoding/global/security/config/PasswordEncoderConfig.java
Labels: refactor

#124 refactor: change the SystemUuidHolder type to UuidHolder
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/domain/CodeRoom.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/global/s3/service/S3ServiceImpl.java
Labels: refactor

#125 test : 댓글 작성 테스트
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
  src/test/java/com/gagoo/thiscoding/domain/mock/TestContainer.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: ✅ Test

#126 test : 댓글 작성 테스트
  src/main/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImpl.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyWriteServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeUserRepository.java
  src/test/java/com/gagoo/thiscoding/global/security/infrastructure/FakeSecurityUtils.java
Labels: ✅ Test

#127 test : 특정 게시물 댓글 전체조회
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyReadServiceTest.java
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/service/ReplyServiceImplTest.java
  src/test/java/com/gagoo/thiscoding/domain/mock/FakeReplyRepository.java
Labels: ✅ Test

#128 test : Board 순수 도메인 생성 테스트
  src/test/java/com/gagoo/thiscoding/domain/mongo/board/domain/BoardTest.java
Labels: ✅ Test

#129 test(chore) : 오탈자 ; 삭제
  src/test/java/com/gagoo/thiscoding/domain/maria/reply/domain/ReplyTest.java
Labels: 🔨 Fix, ✅ Test

#130 fix: 일부 변경되지 않은 UUID 타입을 String 타입으로 변경
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/CodeRoomController.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/controller/port/CodeRoomService.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/Impl/CodeRoomRepositoryImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/infrastructure/jpa/CodeRoomJpaRepository.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/CodeRoomServiceImpl.java
  src/main/java/com/gagoo/thiscoding/domain/maria/coderoom/service/port/CodeRoomRepository.java
Labels: 🔨 Fix
